### PR TITLE
Define app services and DTOs for Cases & Customers

### LINKED ISSUE #45: Design application services for Customers and Contacts

### LINKED ISSUE #46: Design application services for Cases and Action Items

### PR DESCRIPTION
**Pull request by dougwaldron**
*This PR is cumulative with PR #67.*

The Casework service includes Action Item services and DTOs. Similarly, the Customer service includes Contacts.

I also added a new "Staff" role and a dev setting to log in as Staff.

This PR unfortunately includes a lot of noise because I renamed some of the app services and namespaces.

closes #46 
closes #45

### CODE REVIEW

**Review by dougwaldron — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

    
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)

**Comment by dougwaldron** [comment]
I need to fix some failing tests first.

**Review by tom-karasch — APPROVED** [review]
Looks Great. You are really powering through this fast.

**Comment by dougwaldron** [comment]
> Looks Great. You are really powering through this fast.

No moss growing under my feet! Thanks for the quick reviews.

**Pull request merged**
