### PR TITLE
Implement Casework application service

### LINKED ISSUE #51: Implement local repository for Cases (and also Action Items and Agencies)

### LINKED ISSUE #55: Implement Case/Action Item application service

### PR DESCRIPTION
**Pull request by dougwaldron**
*This PR is cumulative with PR #70.*

Implement the `ICustomerService` interface, which includes both Casework and Action Item services. This also required implementing the Action Item and Agency repositories in Local.

closes #55 
closes #51

### CODE REVIEW

**Review by dougwaldron — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

    
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)

**Review by tom-karasch — CHANGES_REQUESTED** [review]
Does this need to be addressed before merge?
image

**Comment by dougwaldron** [comment]
> I did receive one test error. I don't know if this is something involved with this pull request. 

I get the same error occasionally, but not reliably. I don't know what's causing it. Try rebuilding and then re-running the unit tests.

**Review by tom-karasch — APPROVED** [review]

**Comment by tom-karasch** [comment]
Rebuilt and it is testing correctly now

**Pull request merged**
