### PR TITLE
Implement contact phone number editing

### PR DESCRIPTION
**Pull request by dougwaldron**
This took a while to get working right, and it feels really over-engineered! Let me know if anything doesn't make sense.

The first couple of commits are just fixes for existing bugs.

The commit about explicitly managing phone number IDs addresses two issues:

1. I originally handled phone numbers as a simple list with no IDs -- a contact can have multiple phone numbers, but no number takes precedence over the others, and EF handles that situation seamlessly. But that ended up making it difficult and tedious, for example, to delete a number from the list. 

    EF was already generating an ID behind the scenes anyway for its own convenience; I just made it available to the rest of the program to use. See [this article](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities#collections-of-owned-types) if you want to learn more about how that worked.

5. Creating IDs for new data is easy when the ID is a `guid` since in-memory data and entity framework both work the same way if you explicitly generate an ID. But when the ID is an `int`, it's trickier. When using in-memory data, you have to add the ID yourself, but when using Entity Framework, you have to leave the ID empty (actually zero), so EF can generate the next sequential ID from the database. Otherwise you get `IDENTITY_INSERT` errors. That's why there's a new `GetNextPhoneNumberId` method in the Contact repository.

The remaining commits are for implementing the front end.

### CODE REVIEW

**Review by tom-karasch — APPROVED** [review]
Works well. All tests look good and pass.
Excellent!

**Comment by tom-karasch** [comment]
I wrote a large comment here to you, Doug. But, it was deleted because you did another commit. LOL
I was saying how much this will help with FMS. Now I will have to add multiple contacts for each Facility and this phone number addition is great reference!

**Comment by dougwaldron** [comment]
> I wrote a large comment here to you, Doug. But, it was deleted because you did another commit. 

Ouch! Sorry about that; I didn't know that would happen...

**Comment by tom-karasch** [comment]
Yes, I guess because I started writing my comment, then you made another commit, I was not allowed to save my comment without fetching your commit, and It didn't save the comment. Just FYI.

**Pull request merged**
