### PR TITLE
Add SIC code field to Customers

### PR DESCRIPTION
**Pull request by dougwaldron**
Also migrates data from the old database.

Code has been deployed to DEV server for testing.

### CODE REVIEW

**Review by tom-karasch — DISMISSED** [review]
Looks great Doug! All tests passed and SIC codes work fine!

**Comment by tom-karasch** [comment]
> Also migrates data from the old database.
> 
> Code has been deployed to DEV server for testing.

Doug, what is the URL. I don't see one setup for it.

**Comment by dougwaldron** [comment]
> Doug, what is the URL? I don't see one setup for it.

https://dev-air.gaepd.org/sbeap

**Comment by tom-karasch** [comment]
> > Doug, what is the URL? I don't see one setup for it.
> 
> https://dev-air.gaepd.org/sbeap

Thanks. I got in, but have no user roles and cannot see anything. But, that's OK, I used my IDE to open and test everything

**Comment by dougwaldron** [comment]
QA complete

**Comment by dougwaldron** [comment]
UAT DB lacks the `AirBranchCustomerId` column blocking a clean data migration so I requested a DB refresh from prod.

**Review by tom-karasch — DISMISSED** [review]
As far as I can tell your logic works. Looks good as long as your select statements are giving you the results you expect to see.

**Pull request merged**
