### PR TITLE
Implement local repository for Action Item Types

### PR DESCRIPTION
**Pull request by tom-karasch**
WIP for review
Doug, am I on the right track with this. Am I missing something?

### CODE REVIEW

**Review by dougwaldron — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

    
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)

**Comment by tom-karasch** [comment]
Added Tests for Action Item Type Local Repository. Tests successfully ran

**Comment by dougwaldron** [comment]
> WIP for review Doug, am I on the right track with this. Am I missing something?

Yeah, it all looks great! 

Is this still a WIP or is it ready to merge? Next time, you can open the PR as a draft if you want early feedback.

**Review by dougwaldron — APPROVED** [review]
👍🏼

**Pull request merged**
