### PR TITLE
Enable customer search by city

### PR DESCRIPTION
**Pull request by dougwaldron**

### CODE REVIEW

**Review by dougwaldron — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

    
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)

**Review by tom-karasch — COMMENTED** [review]
Hi Doug,
Tests passed and search works fine. However, the search results columns are not aligned and look like this: 
image

**Comment by dougwaldron** [comment]
> Hi Doug, Tests passed and search works fine. However, the search results columns are not aligned and look like this: 

Good catch! Fixed in latest commit.

**Review by tom-karasch — APPROVED** [review]
Looks great now, Doug. Search works well with both site and mailing addresses. Very cool!

**Pull request merged**
