### PR TITLE
Implement the main customer pages

### PR DESCRIPTION
**Pull request by dougwaldron**
This PR implements the Customer Search, Add, and Details pages.

Also included:

- Adjusted the entities to make some properties nullable.
- Refactored the "Create" methods in the entity managers.
- Added an "Admin" role.
- Modified the relevant DTOs.
- Added validators and permissions handlers for Customer and Contact.
- Added a bunch of Razor display templates and editor templates.

### CODE REVIEW

**Review by dougwaldron — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

    
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)

**Review by tom-karasch — APPROVED** [review]
Although I have even more questions, it all looks great. Asking me to review this is like asking a lawnmower mechanic to review changes to a Formula 1 race car. LOL

**Comment by dougwaldron** [comment]
@tom-karasch Sorry for spamming you with all these failed tests! It took a few tries to get the proper syntax right for fixing the GitHub actions.

**Comment by tom-karasch** [comment]
Good catch finding that the issue was the .NET and SDK versions. That would have driven me nuts tracking that down.

**Pull request merged**
