### PR TITLE
Implement additional Customer pages

### PR DESCRIPTION
**Pull request by dougwaldron**
Implements the edit, delete, and restore pages for Customers.

*This PR is dependent on #90.*

### CODE REVIEW

**Review by dougwaldron — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

    
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)

**Review by tom-karasch — DISMISSED** [review]
Code looks fine although with my current credentials I do not have access to "restore" pages. 
All tests passed. 
Sorry for the delay. I have to update VS and reboot twice to run App. Kept freezing on build.

**Comment by dougwaldron** [comment]
> Code looks fine although with my current credentials I do not have access to "restore" pages. 

To change your access level, add an "appsettings.Development.json" file with a `DevSettings` section in the WebApp folder. See [the Readme file](https://github.com/gaepdit/sbeap/blob/ab0bbd4aaa37e4c93fb068ddad685d93ee3922a6/README.md#development-settings) for instructions and descriptions of each setting. 

"Restore" should have identical access requirements as "Delete" so please let me know if that's not the case.

I'm hoping that when you test functionality that depends on access level that you test with various combinations of "authenticated", "staff", or "admin". Also, when testing functionality that includes saving data, please test at least once with `UseInMemoryData` set to `false` so that Entity Framework will be used. (When set to `true` the app should start up and run a bit faster, but EF won't get tested.)

**Comment by tom-karasch** [comment]
Doug I am experimenting with the devsettings and I came across this: 
image
image
Same is true for Delete and restore case. 
Is this supposed to be here or just for dev, to show GUID??

I changed Roles of Gen User2 to Add SBEAP Admin. It works to change roles, but I cannot test to see if the roles work like that, because I cannot login as a different user after changing another User's roles. But, I am assuming it works. 

All seems to work fine for all user types and with Local and EF data. Looks very good!

**Comment by tom-karasch** [comment]
Doug, 
Is appsettings.json in the Git ignore? Should it be? 
I removed the "Devsettings" section from it and put it in "appsettings.Development.json". Is it supposed to stay in "appsettings.json", and is ignored if a separate  "appsettings.Development.json" file exists, and has a "Devsettings" section?
I apologize in advance for my ignorance

**Comment by tom-karasch** [comment]
Nevermind. I played with it more and answered my own previous question.

**Comment by dougwaldron** [comment]
> Doug I am experimenting with the devsettings and I came across this: Same is true for Delete and restore case. Is this supposed to be here or just for dev, to show GUID??

Whoops! I misunderstood your thumbs up above and already merged this. No, the GUID is not supposed to show up. [Bug introduced here](https://github.com/gaepdit/sbeap/pull/91/commits/106c38cad7be0e847a3305589c2d119e921196f8#diff-72da9eb92e8bb5fbd60cfc00a286cd24dbb82e2fb9f5b32b393f2b9827d0b359).

I'll fix it.

**Pull request merged**
